export default [
  {
    jobId: "1",
    jobTitle: "Job 1",
    jobDescription: "Some job",
    companyName: "company",
    companyContact: "someemail@something.com",
    appliedVia: "LinkedIn",
    status: "Application sent",
    remarks: "Rejected at the second phase",
    open: false,
    feedback: "feedback point 1",
  },
  {
    jobId: "2",
    jobTitle: "Job 2",
    jobDescription: "Some job",
    companyName: "company",
    companyContact: "someemail@something.com",
    appliedVia: "LinkedIn",
    status: "Application sent",
    remarks: "Waiting for a reply",
    open: true,
    feedback: "feedfback point 2",
  },
  {
    jobId: "3",
    jobTitle: "Job",
    jobDescription: "Some job",
    companyName: "company",
    companyContact: "someemail@something.com",
    appliedVia: "LinkedIn",
    status: "Application sent",
    remarks: "Rejected at the second phase",
    open: false,
    feedback: "some other feedback",
  },
];
